---
title: "Data Dictionary"
author: "Hanley's Lab"
date: "`r Sys.Date()`"
output:
    rmarkdown::html_vignette:
        toc: true 
vignette: >
  %\VignetteIndexEntry{Data Dictionary}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This data dictionary contains tables from each of the raw data variables as well
as the added variables, with information on what the variable was renamed to,
it's units, and a description of the variable. It also contains information on
adding to the dictionary and renaming `.yaml` files.

# Contents of the `.yaml` dictionary (rename) files

Firstly, [`.yaml`](https://en.wikipedia.org/wiki/YAML) is a structured data
storage format that is easy to read and easy to use. The main goal of the
`.yaml` dictionary files are to allow an easy way to add a dictionary entry and
to easily create dictionary tables. The secondary goal is to allow renaming of
variables and to generate documentation for variables from `data-raw/` and from
variables added to the dataset during the cleaning and managing phase.

For any new raw data file, create a new `.yaml` file specific to that data file
using a text editor (eg. [RStudio](https://www.rstudio.com/)) in the folder
`inst/rename`. Each `.yaml` file must contain the following for each variable
entry:

```
Variable:
    - renamed:
    - unit: 
    - type: 
    - description:
```

- **renamed:** New variabe name; see the next section.
- **unit:** Unit for the variable. For instance, for `Weight`, the unit is `kg`.
If there is no unit, set as `NA`. For discrete variables, define the levels, for
instance `0=no, 1=yes`.
- **type:** Indicates the type of value the variable is. Either `Numeric`,
`Discrete`, or `Date`.
- **description:** A brief description or definition of the variable.

## Variable renaming rules and suggestions

Variables renamed to `- renamed: NA` means they will be dropped from the 
dataset. Within each data file, make sure that subject ID is renamed as `SID`.
You need to rename variables to have no spaces and with the first letter of each word
capitalized. For instance, `diabetes status` is set as
`- renamed: DiabetesStatus` or `Q07a` is set as `- renamed: TobaccoUse`.

# Data Dictionary Tables

These tables contain all the variables within the PROMISE dataset, including
from the original raw data files. Variables renamed as NA were removed from the
final `PROMISE_data`. The dictionary functions are part of the [PROMISE.methods]
package.

```{r dictionary_tables, results='asis'}
library(PROMISE.methods)
options(PROMISE.yaml.path = system.file('rename', package = 'PROMISE'))
generate_dictionary()
```
